const data = [
  {
    dayNum: 1,
    total: 0.01,
    inventory: [],
  },
  {
    dayNum: 1,
    total: 0.0,
    inventory: ["1 Pen"],
  },
  {
    dayNum: 1,
    total: 1.0,
    inventory: [],
  },
  {
    dayNum: 1,
    total: 0,
    inventory: ["1 Water Bottle"],
  },
  {
    dayNum: 1,
    total: 2,
    inventory: [],
  },
  {
    dayNum: 1,
    total: 0,
    inventory: ["2 Water Bottles"],
  },
  {
    dayNum: 1,
    total: 10.5,
    currencyConvert: "€10.00",
    inventory: ["1 Water bottle"],
    note: "Thank you so much, Fionn!",
  },
  {
    dayNum: 1,
    total: 10.5,
    currencyConvert: "€10.00",
    inventory: [],
  },
  {
    dayNum: 1,
    total: 10.5,
    inventory: [],
  },
  {
    dayNum: 1,
    total: 7.91,
    inventory: ["12 Water Bottles"],
  },
  {
    dayNum: 1,
    total: 4.42,
    inventory: ["12 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 8.42,
    inventory: ["10 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 13.42,
    inventory: ["8 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 15.42,
    inventory: ["7 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 35.42,
    inventory: ["6 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
    note: "Let's go Tommy!",
  },
  {
    dayNum: 1,
    total: 37.42,
    inventory: ["5 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 42.42,
    inventory: ["3 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 44.42,
    inventory: ["2 Water Bottles", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 48.42,
    inventory: ["1 Poster", "2 Markers + Eraser", "String"],
    note: "Sold all the water :)",
  },
  {
    dayNum: 1,
    total: 31.69,
    inventory: ["48 Sodas", "1 Poster", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 4.33,
    inventory: [
      // 27.36 for the cooler
      "48 Sodas",
      "1 Cooler",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 1.5,
    inventory: [
      "48 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 3.5,
    inventory: [
      "47 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 28.5, // paid $25 for 1 soda lol
    inventory: [
      "46 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 32.5,
    inventory: [
      "44 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 34.5,
    inventory: [
      "43 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 36.5,
    inventory: [
      "42 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 38.5,
    inventory: [
      "41 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 40.5,
    inventory: [
      "40 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 42.5,
    inventory: [
      "40 Sodas", // tip from guy that wanted water lol
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 44.5,
    inventory: [
      "39 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 46.5,
    inventory: [
      "37 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 47.5,
    inventory: [
      "36 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 49.5,
    inventory: [
      "35 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 51.5,
    inventory: [
      "34 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 57.48,
    inventory: [
      "30 Sodas",
      "1 Cooler",
      "Ice",
      "1 Poster",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 1,
    total: 57.48,
    inventory: ["?? Sodas", "1 Cooler", "Ice", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 84.84,
    inventory: ["2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 78.84,
    inventory: ["4 Tacos", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 78.84,
    inventory: ["2 Markers + Eraser", "String"],
  },
  {
    dayNum: 1,
    total: 42.7,
    inventory: ["Hammock", "Toiletries", "2 Markers + Eraser", "String"],
    donations: 0,
  },
  {
    dayNum: 2,
    total: 38.98, // break fast
    inventory: ["Hammock", "Toiletries", "2 Markers + Eraser", "String"],
  },
  {
    dayNum: 2,
    total: 3.98,
    inventory: [
      "Bike",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 2,
    total: 16.32,
    inventory: [
      "Bike",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 2,
    total: 26.73,
    inventory: [
      "Bike",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 2,
    total: 20.57,
    inventory: [
      "Bike",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 2,
    total: 15.06,
    inventory: [
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 2,
    total: 31.31,
    inventory: [
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 2,
    total: 43.05,
    inventory: [
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    donations: 0,
  },
  {
    dayNum: 3,
    total: 15.69,
    inventory: [
      "Bike",
      "Cooler",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 8.4,
    inventory: [
      "Bike",
      "Cooler",
      "40 Water Bottles",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 4.76,
    inventory: [
      "Bike",
      "Cooler",
      "40 Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 9.76,
    inventory: [
      "Bike",
      "Cooler",
      "39 Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 14.76,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 16.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 18.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 28.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 32.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 34.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 40.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 42.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 44.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 46.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 50.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 55.67,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 56.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 61.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 63.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 65.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 70.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 79.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 57.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    note: "The great $20 change mix-up",
  },
  {
    dayNum: 3,
    total: 83.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    note: "JK, he just forgot to give the 20",
  },
  {
    dayNum: 3,
    total: 85.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 87.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 92.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 98.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 102.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 103.4,
    inventory: [
      "Bike",
      "Cooler",
      "?? Water Bottles",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 108.4,
    inventory: [
      "Bike",
      "Cooler",
      "0 Water Bottles!",
      "Ice",
      "Sign",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 135.76,
    inventory: [
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 128.92, // burrito
    inventory: [
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 98.68, // burrito
    inventory: [
      "Bus Ticket!",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 3,
    total: 110.75, // door dash pay adjustment
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    donations: 11000,
    topDonations: [
      { name: "MrWhoseTheBoss", amount: "5000" },
      { name: "Isaiah Photo", amount: "5000" },
      { name: "Leon Hendrix", amount: "1000" },
    ],
    mealsDonated: 336050,
  },
  {
    dayNum: 4,
    total: 110.75,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.29, // breakfast
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.31,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.34,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.37,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.4,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.43,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.46,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.51,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.54,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.57,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.6,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.65,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.68,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.71,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.74,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.79,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.81,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.86,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.89,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.92,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.95,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 0,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    note: ":))))))", // 4:16 of day 4 video
  },
  {
    dayNum: 4,
    total: 101.95,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 101.29, // just recycled the cans instead of cashing them in
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 90.49,
    inventory: [
      "Rental Bike",
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 109.38,
    inventory: [
      "Rental Bike",
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 115.58,
    inventory: [
      "Rental Bike",
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 123.33,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 128.58,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 128.58,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    note: "AMAZING bike advice from Richard :) Richard is my hero!",
  },
  {
    dayNum: 4,
    total: 136.58,
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 129.74, // burrito
    inventory: [
      "Bus Ticket",
      "Bike",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 154.74,
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 144.12, // bus snackies
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 4,
    total: 144.12, // bus snackies
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    donations: 26069,
    topDonations: [
      { name: "Jordan Welch", amount: "5069" },
      { name: "MrWhoseTheBoss", amount: "5000" },
      { name: "Isaiah Photo", amount: "5000" },
      { name: "Night Media", amount: "5000" },
      { name: "Leon Hendrix", amount: "1000" },
      { name: "Shervin Shares", amount: "1000" },
      { name: "Colby Matrel", amount: "1000" },
      { name: "Hope Scope", amount: "1000" },
      { name: "Miguel Baligod", amount: "1000" },
      { name: "Smequle", amount: "1000" },
    ],
    mealsDonated: 611163,
  },
  {
    dayNum: 5,
    total: 114.55, // uber to bus station
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 5,
    total: 109.64, // uber tip
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 5,
    total: 106.34,
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 5,
    total: 105.94, // gas station tip
    inventory: [
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 5,
    total: 85.66,
    inventory: [
      "Hotel Room (1 night)",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 5,
    total: 8.32,
    inventory: [
      "Hotel Room (4 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 5,
    total: 6.32,
    inventory: [
      "Hotel Room (4 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    note: "(never play slots lol)",
  },
  {
    dayNum: 5,
    total: 6.32,
    inventory: [
      "Hotel Room (4 nights)",
      "Bus Ticket",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
    donations: 26069,
    topDonations: [
      { name: "Jordan Welch", amount: "5069" },
      { name: "MrWhoseTheBoss", amount: "5000" },
      { name: "Isaiah Photo", amount: "5000" },
      { name: "Night Media", amount: "5000" },
      { name: "Leon Hendrix", amount: "1000" },
      { name: "Shervin Shares", amount: "1000" },
      { name: "Colby Matrel", amount: "1000" },
      { name: "Hope Scope", amount: "1000" },
      { name: "Miguel Baligod", amount: "1000" },
      { name: "Smequle", amount: "1000" },
    ],
    mealsDonated: 750000,
  },
  {
    dayNum: 6,
    total: 5.24,
    inventory: [
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
      "2 Markers + Eraser",
      "String",
    ],
  },
  {
    dayNum: 6,
    total: 0.8,
    inventory: [
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 0.8,
    inventory: [
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 20.8,
    inventory: [
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
    note: "Tip from Tiffany!",
  },
  {
    dayNum: 6,
    total: 80.8,
    inventory: [
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 75.39, // mcdanks
    inventory: [
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 70.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
    note: "comedy time :)",
  },
  {
    dayNum: 6,
    total: 80.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 79.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 84.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 86.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 87.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 88.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 89.59,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 90.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 92.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 97.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 102.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 103.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 105.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 125.87,
    inventory: [
      "Poster, String, Bowl",
      "Cleaning Supplies",
      "Hotel Room (3 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 6,
    total: 125.87,
    inventory: ["Hotel Room (3 nights)", "Blanket", "Hammock", "Toiletries"],
    donations: 43069,
    topDonations: [
      { name: "Skip The Tutorial", amount: "10000" },
      { name: "Jordan Welch", amount: "5069" },
      { name: "MrWhoseTheBoss", amount: "5000" },
      { name: "Isaiah Photo", amount: "5000" },
      { name: "Night Media", amount: "5000" },
      { name: "Jake", amount: "5000" },
      { name: "Leon Hendrix", amount: "1000" },
      { name: "Shervin Shares", amount: "1000" },
      { name: "Colby Matrel", amount: "1000" },
      { name: "Hope Scope", amount: "1000" },
      { name: "Miguel Baligod", amount: "1000" },
      { name: "Smequle", amount: "1000" },
      { name: "Colin and Samir", amount: "1000" },
      { name: "Danny and Meghan", amount: "1000" },
    ],
    mealsDonated: 934020,
  },
  {
    dayNum: 7,
    total: 123.71,
    inventory: ["Hotel Room (2 nights)", "Blanket", "Hammock", "Toiletries"],
  },
  {
    dayNum: 7,
    total: 45.04,
    inventory: [
      "48 Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 50.04,
    inventory: [
      "46 Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 55.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 57.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 61.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 66.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 68.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 70.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 75.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 77.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 92.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 94.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 96.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 98.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 103.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 108.04,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 109.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 114.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 116.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 126.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 127.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 129.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 131.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 133.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 135.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 140.84,
    inventory: [
      "?? Water Bottles",
      "Cooler",
      "Ice",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 205.86,
    inventory: ["Hotel Room (2 nights)", "Blanket", "Hammock", "Toiletries"],
  },
  {
    dayNum: 7,
    total: 81.88,
    inventory: [
      "Flight",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 73.7, // burrito
    inventory: [
      "Flight",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
  },
  {
    dayNum: 7,
    total: 73.7,
    inventory: [
      "Flight",
      "Hotel Room (2 nights)",
      "Blanket",
      "Hammock",
      "Toiletries",
    ],
    donations: 167500,
    topDonations: [
      { name: "---", amount: "---" },
      { name: "Blake Olson", amount: "50000" },
      { name: "Skip The Tutorial", amount: "10000" },
      { name: "Jordan Welch", amount: "5069" },
      { name: "Matt Rutkowsku", amount: "5000" },
      { name: "growwithjo", amount: "5000" },
      { name: "Caylus / Infinite", amount: "5000" },
      { name: "Jake", amount: "5000" },
      { name: "Mintra.info", amount: "5000" },
      { name: "Night Media", amount: "5000" },
      { name: "Neil from Whalar", amount: "5000" },
      { name: "MrWhoseTheBoss", amount: "5000" },
      { name: "Isaiah", amount: "5000" },
      { name: "M", amount: "2500" },
      { name: "Cirque du Soleil", amount: "1000" },
      { name: "dr ryan", amount: "1000" },
      { name: "Sean Tao", amount: "1000" },
      { name: "Eze Adventurer", amount: "1000" },
      { name: "Humphrey Yang", amount: "1000" },
    ],
    mealsDonated: 2234000,
  },
];

/**

donations: 26069,
topDonations: [
  { name: "Jordan Welch", amount: "5069" },
  { name: "MrWhoseTheBoss", amount: "5000" },
  { name: "Isaiah Photo", amount: "5000" },
  { name: "Night Media", amount: "5000" },
  { name: "Leon Hendrix", amount: "1000" },
  { name: "Shervin Shares", amount: "1000" },
  { name: "Colby Matrel", amount: "1000" },
  { name: "Hope Scope", amount: "1000" },
  { name: "Miguel Baligod", amount: "1000" },
  { name: "Smequle", amount: "1000" },
],
mealsDonated: 750000,

 */
export { data };
